export enum ActionType {
    // user scripts
    FETCH_USER_SCRIPTS = "FETCH_USER_SCRIPTS",
    NEW_USER_SCRIPT = "NEW_USER_SCRIPT",
    REMOVE_USER_SCRIPT = "REMOVE_USER_SCRIPT",

    // chain gas price
    FETCH_LATEST_GAS_PRICE = "FETCH_LATEST_GAS_PRICE",

    // prices
    FETCH_DAEM_ETH_PRICE = "FETCH_DAEM_ETH_PRICE",

    // scripts creation queue
    CLEAN_WORKBENCH = "CLEAN_WORKBENCH",
    ADD_TO_WORKBENCH = "ADD_TO_WORKBENCH",

    // wallet
    FETCH_DAEM_BALANCE = "FETCH_DAEM_BALANCE",
    FETCH_ETH_BALANCE = "FETCH_ETH_BALANCE",
    FETCH_BALANCES = "FETCH_BALANCES",
    FETCH_MM_INFO = "FETCH_MM_INFO",
    CLEAN_MM_INFO = "CLEAN_MM_INFO",

    // user
    WALLET_UPDATE = "WALLET_UPDATE",
    FETCH_USER = "FETCH_USER",
    SET_TX_AS_SEEN = "SET_TX_AS_SEEN",
    UPDATE_USERNAME = "UPDATE_USERNAME",
    UPDATE_TUTORIAL_TOOLTIP = "UPDATE_TUTORIAL_TOOLTIP",
    UPDATE_USER_STATS = "UPDATE_USER_STATS",

    // treasury
    FETCH_TREASURY_STATS = "FETCH_TREASURY_STATS"
}
