export enum ActionType {
    // user scripts
    FETCH_USER_SCRIPTS = "FETCH_USER_SCRIPTS",
    NEW_USER_SCRIPT = "NEW_USER_SCRIPT",
    REMOVE_USER_SCRIPT = "REMOVE_USER_SCRIPT",
    FETCH_EXECUTABLE_SCRIPTS = "FETCH_EXECUTABLE_SCRIPTS",
    REMOVE_EXECUTABLE_SCRIPT = "REMOVE_EXECUTABLE_SCRIPT",
    SET_SCRIPTS_LOADING = "SET_SCRIPTS_LOADING",

    // chain gas price
    FETCH_LATEST_GAS_PRICE = "FETCH_LATEST_GAS_PRICE",

    // prices
    FETCH_DAEM_ETH_PRICE = "FETCH_DAEM_ETH_PRICE",

    // scripts creation queue
    CLEAN_WORKBENCH = "CLEAN_WORKBENCH",
    ADD_TO_WORKBENCH = "ADD_TO_WORKBENCH",

    // wallet
    WALLET_UPDATE = "WALLET_UPDATE",
    AUTH_CHECK = "AUTH_CHECK",
    FETCH_DAEM_BALANCE = "FETCH_DAEM_BALANCE",
    FETCH_ETH_BALANCE = "FETCH_ETH_BALANCE",
    SET_TX_AS_SEEN = "SET_TX_AS_SEEN",

    // gas tank
    GAS_TANK_BALANCE = "GAS_TANK_BALANCE",
    GAS_TANK_CLAIMABLE = "GAS_TANK_CLAIMABLE",

    // tip jar
    TIP_JAR_BALANCE = "TIP_JAR_BALANCE",

    // staking
    STAKING_BALANCE = "STAKING_BALANCE",
    STAKING_CLAIMABLE = "STAKING_CLAIMABLE",

    // treasury
    FETCH_TREASURY_STATS = "FETCH_TREASURY_STATS"
}
