name: Deploy Executor Frontend

on:
  push:
    branches:
      - master
    paths:
      - "executor-frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: |
          cd executor-frontend/
          npm install

      # - name: test
      #   run: |
      #     cd executor-frontend/
      #     npm run test:ci

      - name: Build
        run: |
          cd executor-frontend/
          npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: depl-executor-frontend
          FOLDER: executor-frontend/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Executor frontend tested, built and deployed"
