name: Deploy App Frontend

on:
  push:
    branches:
      - master
    paths:
      - "app-frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: |
          cd app-frontend/
          npm install

      - name: test
        run: |
          cd app-frontend/
          npm run test:ci

      - name: Build
        run: |
          cd app-frontend/
          npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: depl-frontend
          FOLDER: app-frontend/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "App frontend tested, built and deployed"
