name: Deploy Bots Backend

on:
  push:
    branches:
      - master
    paths:
      - "bots-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Test
        env:
          MONGO_DB_CONN_STRING: not_used_in_tests
          KOVAN_RPC: not_used_in_tests
          MUMBAI_RPC: not_used_in_tests
        run: |
          cd bots-backend/
          npm install
          npm run test:ci

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: depl-daemonic-bots
          FOLDER: bots-backend
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Bots backend tested and deployed"
