name: Deploy Db-Schema package

on:
  push:
    branches:
      - master
    paths:
      - "npm-packages/db-schema/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: |
          cd npm-packages/db-schema/
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
