name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: |
          cd frontend/
          npm install

      - name: test
        run: |
          cd frontend/
          npm run test

      - name: Build
        run: |
          cd frontend/
          npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy-frontend
          FOLDER: frontend/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Frontend tested, built and deployed"
